spring:
  datasource:
    url: jdbc:mysql://121.5.66.99:3306/privalue_notice?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=CST
    username: root
    password: hty1095470074
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
dubbo:
  application:
    name: notice-service
    owner: privalue
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: zookeeper://121.5.66.99:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://121.5.66.99:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.privalue.notice.services

logging:
  level:
    com.privalue: debug

