spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:com/privalue/notice/dal/presistence/*Mapper.xml
  type-aliases-package: com.privalue.notice.dal.entitys

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
