spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/privalue?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=CST
    username: root
    password: hty1095470074
