dubbo:
  application:
    name: gateway
    owner: privalue
  registry:
    address: zookeeper://121.5.66.99:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://121.5.66.99:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.privalue.gateway
logging:
  level:
    com.privalue: debug
